name: sshnoports
publish_to: none

version: 5.12.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core:
    path: "../noports_core"
  at_onboarding_cli: ^1.13.0
  at_commons: ^5.6.1
  at_cli_commons: ^3.0.1
  at_client: ^3.8.0
  args: 2.7.0
  socket_connector: 2.4.1
  dartssh2: 2.11.0
  duration: 4.0.3
  at_utils: 3.3.0
  logging: 1.3.0
  chalkdart: ^2.3.3
  yaml: 3.1.3

dependency_overrides:
  dartssh2:
    git:
      url: https://github.com/atsign-foundation/dartssh2
      ref: trunk

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  mocktail: ^1.0.4
  build_runner: 2.10.0
  build_version: ^2.1.3
