name: sshnoports
publish_to: none

version: 5.6.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  noports_core:
    path: "../noports_core"
    version: 6.2.1
  at_onboarding_cli: 1.8.2
  at_cli_commons: 1.3.0
  at_client: 3.4.0
  args: 2.6.0
  socket_connector: 2.3.3
  dartssh2: 2.11.0
  duration: 4.0.3
  at_utils: 3.0.19
  logging: 1.3.0
  chalkdart: 2.2.1
  yaml: 3.1.3

dependency_overrides:
  dartssh2:
    git:
      url: https://github.com/atsign-foundation/dartssh2
      ref: trunk
  args:
    git:
      ref: gkc/show-aliases-in-usage
      url: https://github.com/gkc/args

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
  mocktail: ^1.0.4
  build_runner: ^2.4.14
  build_version: ^2.1.1
