name: dockerhub_sshnpd

on:
  workflow_dispatch:
  push:
    tags:
      - "t*.*.*"

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Extract version for docker tag
      - name: Get version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      # Check for whether this is a pre-release
      - id: prerelease
        name: Check for pre-release
        run: |
          RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.VERSION }}")
          echo "$RELEASE_JSON"
          PRERELEASE=$(echo "$RELEASE_JSON" | jq -r '.prerelease')
          if [ $PRERELEASE == 'false' ]; then
            echo "Is latest release - do some work"
          else
            echo "Is a pre-release"
          fi
