name: Promote a release

on:
  push:
    tags:
      - 'p*.*.*'

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  get_canary_sboms:
    name: Get the Canary SBOMs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - name: Get latest canary tag
        run: |
          CANARY=$(git tag --sort=-version:refname -l c*.*.* | head -1)
          echo ${CANARY}


#   github-release:
#     name: >-
#       Upload artifacts and generate checksums for provenance
#     #needs: [main_build, other_build, source_tarball]
#     needs: [get_canary_sboms]
#     runs-on: ubuntu-latest
#     outputs:
#       hashes: ${{ steps.hash.outputs.hashes }}
#     permissions:
#       contents: write  # IMPORTANT: mandatory for making GitHub Releases
#       id-token: write  # IMPORTANT: mandatory for sigstore
#       attestations: write
#     steps:
#     - name: Download all the tarballs
#       uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
#       with:
#         path: tarballs/
# #    - name: Generate SBOMs
# #      run: |
# #        syft scan file:./packages/dart/sshnoports/pubspec.lock \
# #          -o 'spdx-json=tarballs/dart_sshnoports_sbom.spdx.json' \
# #          -o 'cyclonedx-json=tarballs/dart_sshnoports_sbom.cyclonedx.json'
#     - name: Move packages for signing
#       run: |
#         cd tarballs
#         echo "Before:"
#         ls -latrR *
#         mv */*.tgz .
#         mv */*.tar.gz .
#         mv */*.zip .
#         rm -Rf -- */
#         echo "After:"
#         ls -latrR *
#     - name: Generate SHA256 checksums
#       working-directory: tarballs
#       run: sha256sum * > checksums.txt
#     - name: Upload artifacts to GitHub Release
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
#       # Upload to GitHub Release using the `gh` CLI.
#       # `dist/` contains the built packages, and the
#       # sigstore-produced signatures and certificates.
#       run: >-
#         gh release upload
#         '${{ github.ref_name }}' tarballs/**
#         --repo '${{ github.repository }}'
#     - id: hash
#       name: Pass artifact hashes for SLSA provenance
#       working-directory: tarballs
#       run: |
#         echo "hashes=$(cat checksums.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
#     - uses: actions/attest-build-provenance@bdd51370e0416ac948727f861e03c2f05d32d78e # v1.3.2
#       with:
#         subject-path: 'tarballs/**'

#   provenance:
#     needs: [github-release]
#     permissions:
#       actions: read # Needed for detection of GitHub Actions environment.
#       id-token: write # Needed for provenance signing and ID
#       contents: write # Needed for release uploads
#     uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0 # 5a775b367a56d5bd118a224a811bba288150a563
#     with:
#       base64-subjects: "${{ needs.github-release.outputs.hashes }}"
#       upload-assets: true
